6. Reshape a 1D array of 12 elements into a 3x4 matrix.

In [2]:
import numpy as np

In [7]:
arr = np.random.randint(0,10 , size=(1,12)).reshape(3,4)
arr

array([[6, 9, 5, 4],
       [4, 2, 0, 9],
       [9, 7, 2, 7]], dtype=int32)

7. Flatten a 3x3 matrix into a 1D array.

In [10]:
arr1 = np.random.randint(0,100,size=(3,3))
print(arr1)

arr1.reshape(1,9)

[[79 36 82]
 [ 0 78 79]
 [91 16 23]]


array([[79, 36, 82,  0, 78, 79, 91, 16, 23]], dtype=int32)

8. Stack two 3x3 matrices horizontally and vertically.

In [19]:
arr2 = np.random.randint(0,100,size=(3,3))
print(arr2)
arr3 = np.random.randint(0,100,size=(3,3))
print("------------")
print(arr3)
print("------------")
print (np.hstack((arr2,arr3)))

print("------------")
print (np.vstack((arr2,arr3)))

[[96 27 75]
 [67 65 64]
 [49 61  8]]
------------
[[89 25 98]
 [68 85 90]
 [88 66 66]]
------------
[[96 27 75 89 25 98]
 [67 65 64 68 85 90]
 [49 61  8 88 66 66]]
------------
[[96 27 75]
 [67 65 64]
 [49 61  8]
 [89 25 98]
 [68 85 90]
 [88 66 66]]


9. Concatenate two arrays of different sizes along a new axis.

In [24]:
arr4 = np.random.randint(0,100,size=(3,2))
print(arr4)
print("------------")
arr5 = np.random.randint(0,100,size=(2,3))
print(arr5)  
print("------------")

np.concat((arr4,arr5),axis=1)

[[86 30]
 [48 22]
 [95 32]]
------------
[[13 36  4]
 [80 61 78]]
------------


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.

In [28]:
arr6 = np.random.randint(0,100 , size=(3,2))
print(arr6)
print("------------")

transpose = arr6.transpose()
print(transpose)
print("------------")

arr7 = transpose.reshape(3,2)
print(arr7)


[[98 42]
 [41 83]
 [93 30]]
------------
[[98 41 93]
 [42 83 30]]
------------
[[98 41]
 [93 42]
 [83 30]]
