1. Create a 3x3 array filled with random integers between 0 and 10. Calculate the sum, mean,
and standard deviation of the array.

In [1]:
import numpy as np 

In [9]:
arr = np.random.randint(0,10 , size = (3,3))
print(arr)



[[4 0 5]
 [6 8 5]
 [9 9 7]]


In [11]:
arr.sum()


np.int64(53)

In [12]:
arr.mean()


np.float64(5.888888888888889)

In [13]:
arr.std()

np.float64(2.6851213274654606)

2. Create a 1D array of 10 elements and compute the cumulative sum of the elements.

In [17]:
arr2 = np.random.randint(0,10 , size = (1,10))
print(arr2)
arr2.cumsum()

[[3 4 0 1 8 1 4 6 4 8]]


array([ 3,  7,  7,  8, 16, 17, 21, 27, 31, 39])

3. Generate two 2x3 arrays with random integers and perform element-wise addition,
subtraction, multiplication, and division.

In [23]:
arr3 = np.random.randint(0,100,size = (2,3))
print(arr3)

print("-----")
arr4 = np.random.randint(0,100,size = (2,3))
print(arr4)



[[81 27  1]
 [35 48 97]]
-----
[[64 38 65]
 [ 7 50 18]]


In [24]:
#multiiplication

arr3 * arr4 

array([[5184, 1026,   65],
       [ 245, 2400, 1746]], dtype=int32)

In [26]:
arr3 + arr4

array([[145,  65,  66],
       [ 42,  98, 115]], dtype=int32)

In [27]:
arr3 - arr4

array([[ 17, -11, -64],
       [ 28,  -2,  79]], dtype=int32)

In [ ]:
arr3 / arr4 

array([[1.265625  , 0.71052632, 0.01538462],
       [5.        , 0.96      , 5.38888889]])

In [37]:
arr3 // arr4 

array([[1, 0, 0],
       [5, 0, 5]], dtype=int32)

4. Create a 4x4 identity matrix.

In [36]:
#identitiy matrix means 1 0 1 i think soo 

arr5 = np.identity(4,dtype = int)
arr5

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

5. Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.

In [39]:
a = np.array([5, 10, 15, 20, 25])
a// 5

array([1, 2, 3, 4, 5])