16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.

In [1]:
import numpy as np

In [16]:
arr = np.random.randint(0,100, size=(3,3))
print(arr)

print("------------------")

arr1 =  np.random.randint(0,100, size=(1,3))
print(arr)

print("------------------")

result = arr + arr1
print(result)

[[89  6 55]
 [16 36 45]
 [37 67 94]]
------------------
[[89  6 55]
 [16 36 45]
 [37 67 94]]
------------------
[[144  95 117]
 [ 71 125 107]
 [ 92 156 156]]


17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.

In [18]:
arr2 = np.random.randint(0,100, size=(1,5))
print(arr2)
print("-------------------")

print(arr2*5)

[[48 38  5  6 55]]
-------------------
[[240 190  25  30 275]]


18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.

In [20]:
arr3 = np.random.randint(0,100, size=(3,3))
print(arr3)
print("-------------------")
arr4 = np.random.randint(0,100, size=(3,1))
print(arr4)
print("-------------------")

result = arr3 - arr4
print(result)

[[43 82 22]
 [23 17 11]
 [58 96 59]]
-------------------
[[63]
 [ 4]
 [39]]
-------------------
[[-20  19 -41]
 [ 19  13   7]
 [ 19  57  20]]


19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.

In [21]:
arr5 = np.random.randint(0,100, size=(3,3))
print(arr5)
print("-------------------")

print(arr5 + 2)

[[82 54 68]
 [18 51 10]
 [89 51 77]]
-------------------
[[84 56 70]
 [20 53 12]
 [91 53 79]]


20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.

In [23]:
arr6 = np.random.randint(0,100, size=(4,1))
print(arr6)
print("-------------------")

arr7 = np.random.randint(0,100, size=(1,5))
print(arr7)
print("-------------------")

arr6 = np.random.randint(0,100, size=(4,1))
print(arr6)
print("-------------------")

arr6 + arr7

[[29]
 [56]
 [18]
 [22]]
-------------------
[[ 9 65 80 71 42]]
-------------------
[[69]
 [98]
 [85]
 [ 7]]
-------------------


array([[ 78, 134, 149, 140, 111],
       [107, 163, 178, 169, 140],
       [ 94, 150, 165, 156, 127],
       [ 16,  72,  87,  78,  49]], dtype=int32)