11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.

In [2]:
import numpy as np

In [18]:
arr = np.random.randint(0,10, size= (1,15))
print(arr)
print("-------------")
print(arr[0, 1:9:2])

[[1 2 0 1 3 9 8 5 2 5 7 5 1 3 7]]
-------------
[2 1 9 5]


12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and
columns 2 to 4.

In [ ]:
arr1 = np.random.randint(0,10, size= (5,5))
print(arr1)

print("-------------")

print(arr1[1:4 , 2:5])

#NOTE - Here we have to add +1 to what we are trying to add

[[4 4 1 1 1]
 [4 0 6 3 0]
 [4 7 6 6 9]
 [1 9 3 5 6]
 [1 4 0 6 3]]
-------------
[[6 3 0]
 [6 6 9]
 [3 5 6]]


13. Replace all elements in a 1D array greater than 10 with the value 10.

In [30]:
arr2 = np.random.randint(0,100, size= (5,5))
print(arr2)
print("-------------")
arr2[arr2 > 10] = 10
print(arr2)

#this is vectorized operations and what it does is loop throught each element 
#after that it assigns a value of 10 if the value is correct 
 

[[85 56 72 72 11]
 [12 66 94 12 97]
 [18 65 74 39 82]
 [67 21  1 46 66]
 [72 31  7 55 53]]
-------------
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10  1 10 10]
 [10 10  7 10 10]]


14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].

In [32]:
arr3 = np.random.randint(0,100, size=(1,15))
print(arr3)
print("-------------")
print(arr3[0 ,0:7:2])

[[19 41 60  7 40 72 79  5  8 20 59 69 22 17 84]]
-------------
[19 60 40 79]


15. Create a 1D array of 10 elements and reverse it using slicing.

In [35]:
arr4 = np.random.randint(0,100, size=(1,10))
print(arr4)
print("-------------")
print(arr4[0,::-1])
print("-------------")

[[ 4 30 28  1  9 88 41 35 77  0]]
-------------
[ 0 77 35 41 88  9  1 28 30  4]
-------------
