In [2]:
import numpy as np

26. Create a 3x3 matrix and find its determinant.

In [3]:
arr3 = np.random.randint(0,100, size=(3,3))
print(arr3)
print("-------------------")

print(np.linalg.det(arr3))

[[48 59  6]
 [77 28 81]
 [49 93 20]]
-------------------
-156659.0


27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to
obtain the identity matrix.

In [11]:
arr4 = np.random.randint(0,100, size=(2,2))
print(arr4)
print("-------------------")
arr5 = np.linalg.inv(arr4)
print(arr5)

print("-------------------")

print(np.dot(arr4, arr5 ))

[[64 64]
 [18 83]]
-------------------
[[ 0.01995192 -0.01538462]
 [-0.00432692  0.01538462]]
-------------------
[[ 1.00000000e+00  0.00000000e+00]
 [-7.45931095e-17  1.00000000e+00]]


28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.

In [14]:
arr6 = np.random.randint(0,100, size=(2,2))
print(arr6)
print("-------------------")

eigenvalues =   np.linalg.eigvals(arr6)
print("Eigen values",eigenvalues)

print("-------------------")

eigenvectors = np.linalg.eig(arr6)
print("Eigen vectors",eigenvectors)



[[69 52]
 [86 74]]
-------------------
Eigen values [  4.58027197 138.41972803]
-------------------
Eigen vectors EigResult(eigenvalues=array([  4.58027197, 138.41972803]), eigenvectors=array([[-0.62810814, -0.59952178],
       [ 0.77812606, -0.80035844]]))


29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.

In [ ]:
arr7 = np.array([[2,3],
                 [4,6]])

arr8 = np.array([5,10])

print(np.linalg.solve(arr7,arr8))

#because the det is 0 it has infinite meny solutions thats why we are having an error 

LinAlgError: Singular matrix

30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original
matrix using the SVD components.

In [ ]:
arr8 = np.random.randint(0,10, size=(3,3))
print(arr8)
print("-------------------")

U , S , VT = np.linalg.svd(arr8)

sigma = np.diag(S)
print(sigma)

print("-------------------")

reconstruction = U @ sigma @ VT
print(reconstruction)


#NOTE - marking this questions for later revision

[[8 6 2]
 [0 5 3]
 [1 0 8]]
-------------------
[[11.5702683   0.          0.        ]
 [ 0.          7.37154931  0.        ]
 [ 0.          0.          3.84566667]]
-------------------
[[ 8.00000000e+00  6.00000000e+00  2.00000000e+00]
 [-1.55895937e-15  5.00000000e+00  3.00000000e+00]
 [ 1.00000000e+00 -1.34619759e-15  8.00000000e+00]]
