In [1]:
import numpy as np

from sklearn.preprocessing import MinMaxScaler

1. Create a NumPy array of random numbers and normalize the data using min-max scaling.

In [2]:
arr = np.random.randint(0,100, size=(3,3),dtype=int)
print(arr)

print("------------------")

scaler = MinMaxScaler()

print(scaler.fit_transform(arr))


[[10 22 76]
 [47 49 11]
 [15 61 23]]
------------------
[[0.         0.         1.        ]
 [1.         0.69230769 0.        ]
 [0.13513514 1.         0.18461538]]


2. Generate a 5x5 matrix with random integers and replace all occurrences of a specific value
with another.

In [3]:
arr2 = np.random.randint(0,10, size=(5,5),dtype=int)
print(arr2)

print("------------------")

arr2[arr2 == 7] = 12
print(arr2)



[[1 7 3 3 6]
 [9 7 1 4 9]
 [4 7 9 7 4]
 [8 1 4 9 8]
 [6 3 0 7 8]]
------------------
[[ 1 12  3  3  6]
 [ 9 12  1  4  9]
 [ 4 12  9 12  4]
 [ 8  1  4  9  8]
 [ 6  3  0 12  8]]


3. Create two NumPy arrays and perform element-wise addition, subtraction, multiplication, and
division.

In [4]:
arr4 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr4)

print("------------------")

arr5 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr5)

print("------------------")

print(arr4 + arr5)

print("------------------")

print(arr4 - arr5)

print("------------------")

print(arr4 * arr5)

print("------------------")

print(arr5 / arr4)

print("------------------")

[[6 4 4]
 [9 8 5]
 [9 4 7]]
------------------
[[8 5 2]
 [6 4 2]
 [2 5 1]]
------------------
[[14  9  6]
 [15 12  7]
 [11  9  8]]
------------------
[[-2 -1  2]
 [ 3  4  3]
 [ 7 -1  6]]
------------------
[[48 20  8]
 [54 32 10]
 [18 20  7]]
------------------
[[1.33333333 1.25       0.5       ]
 [0.66666667 0.5        0.4       ]
 [0.22222222 1.25       0.14285714]]
------------------


4. Solve the system of linear equations: \(3x + 4y = 7\) and \(5x + 2y = 8\) using NumPy.

In [8]:
x = np.array([[3,4],
              [5,6]])

y = np.array([7,8])

print(np.linalg.solve(x,y))

[-5.   5.5]


Create a 3x3 identity matrix using NumPy.

In [ ]:
arr6 = np.identity(3,dtype=int)
print(arr6)

print("------------------")


[[1 0 0]
 [0 1 0]
 [0 0 1]]
------------------


7. Perform matrix multiplication between two 2D arrays.

In [ ]:
arr7 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr7)

print("------------------")

arr8 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr8)

print("------------------")

print(np.dot(arr7,arr8))

print("------------------")

print(arr7*arr8)


[[1 7 7]
 [6 8 3]
 [3 1 2]]
------------------
[[7 2 6]
 [4 3 2]
 [1 3 2]]
------------------
[[42 44 34]
 [77 45 58]
 [27 15 24]]
------------------
[[ 7 14 42]
 [24 24  6]
 [ 3  3  4]]


8. Calculate the dot product and cross product of two vectors using NumPy.

In [ ]:
arr9 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr9)

print("------------------")

arr10 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr10)

print("------------------")

print(np.dot(arr9,arr10))

print("------------------")

print(np.cross(arr9,arr10))


[[5 7 7]
 [1 5 1]
 [1 2 8]]
------------------
[[5 6 8]
 [8 4 5]
 [7 3 1]]
------------------
[[130  79  82]
 [ 52  29  34]
 [ 77  38  26]]
------------------
[[ 14  -5  -5]
 [ 21   3 -36]
 [-22  55 -11]]


9. Generate a NumPy array of 20 random integers and find the unique elements in the array.

In [10]:
arr11 = np.random.randint(1,10, size=(1,20),dtype=int)
print(arr11)

print("------------------")

print(np.unique(arr11))

[[6 1 4 1 4 7 7 2 4 6 4 6 2 7 8 9 2 9 4 3]]
------------------
[1 2 3 4 6 7 8 9]


10. Implement a function using NumPy that returns the inverse of a given matrix.

In [ ]:
def inverse(arr):
    return np.linalg.inv(arr)

arr12 = np.random.randint(1,10, size=(3,3),dtype=int)
print(arr12)

print("------------------")

inverse(arr12)

[[7 8 5]
 [7 2 9]
 [3 8 4]]
------------------


array([[ 0.31067961, -0.03883495, -0.30097087],
       [ 0.00485437, -0.0631068 ,  0.13592233],
       [-0.24271845,  0.15533981,  0.2038835 ]])