21. Compute the square root of each element in a 2D array using vectorized operations.

In [3]:
import numpy as np


In [8]:
arr = np.random.randint(0,100, size=(3,3))
print(arr)
print("-------------------")

np.sqrt(arr)


[[36 69 93]
 [46 96  1]
 [ 8 68 13]]
-------------------


array([[6.        , 8.30662386, 9.64365076],
       [6.78232998, 9.79795897, 1.        ],
       [2.82842712, 8.24621125, 3.60555128]])

22. Calculate the dot product of two 1D arrays of size 5.

In [13]:
arr1 = np.random.randint(0,100, size=(1,5))
print(arr1)
print("-------------------")

arr2 = np.random.randint(0,100, size=(1,5))
print(arr2)
print("-------------------")

print(arr1.dot(arr2.T))


[[23 14 52 94 78]]
-------------------
[[ 7  7  8 36 60]]
-------------------
[[8739]]


23. Perform element-wise comparison of two 1D arrays and return an array of boolean values
indicating where the first array has larger elements.

In [17]:
arr3 = np.random.randint(0,100, size=(3,3))
print(arr3)
print("-------------------")

arr4 = np.random.randint(0,100, size=(3,3))
print(arr4)
print("-------------------")

arr3 > arr4 

[[17 87 89]
 [63 43 49]
 [57 38 60]]
-------------------
[[57 47 36]
 [34 99 85]
 [59 53 84]]
-------------------


array([[False,  True,  True],
       [ True, False, False],
       [False, False, False]])

24. Create a 2D array and apply a vectorized operation to double the value of each element.

In [18]:
arr5 = np.random.randint(0,100, size=(3,3))
print(arr5)
print("-------------------")

arr5*2

[[55 77 46]
 [79 10 71]
 [ 4 40 17]]
-------------------


array([[110, 154,  92],
       [158,  20, 142],
       [  8,  80,  34]], dtype=int32)

25. Create a 1D array of 100 random integers and compute the sum of all even numbers using
vectorized operations.

In [21]:
arr6 = np.random.randint(0,100, size=(1,100))
print(arr6)
print("-------------------")

arr6[arr6 % 2 == 0].sum()


[[ 8  1 13 52 35 98 10 79 81 28 31 80 90 58 71 45 99  5 87 75 76 66 16 91
  45 88 32 39 79 27 12 45 72  6 23 36 78 86 38 41 80 96 41 95 24  9 59 58
  35 38 44 40 22 48 29 50 82 71 48 14 67 76  5 25 31 74 10  0 68 66 22 30
  80 85 12 55 27 60 37 54 25 37 91 17 22 70 87 44 89 97  1 13 23 86 70 13
  81 42 40 60]]
-------------------


np.int64(2660)